services:
  db_events:
    image: postgres:16-alpine
    container_name: events_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_EVENTS_PORT}:${POSTGRES_PORT}"
    volumes:
      - eventapi_events_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  
  db_bookings:
    image: postgres:16-alpine
    container_name: bookings_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_BOOKINGS_PORT}:${POSTGRES_PORT}"
    volumes:
      - eventapi_bookings_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  db_users:
    image: postgres:16-alpine
    container_name: users_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PG_USERS_PORT}:${POSTGRES_PORT}"
    volumes:
      - eventapi_users_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - eventapi_pgadmindata:/var/lib/pgadmin
    depends_on:
      - db_events
      - db_bookings
      - db_users
    restart: unless-stopped

volumes:
  eventapi_events_pgdata:
  eventapi_bookings_pgdata:
  eventapi_users_pgdata:
  eventapi_pgadmindata:
